"""Shared utility layer for reusable core helpers."""

from src.core.utils.file_utils import (
    DEFAULT_MAX_BYTES,
    DEFAULT_MAX_LINES,
    GREP_MAX_LINE_LENGTH,
    TruncationResult,
    detect_line_ending,
    format_size,
    generate_diff_string,
    normalize_to_lf,
    resolve_read_path,
    resolve_to_cwd,
    restore_line_endings,
    strip_bom,
    truncate_head,
    truncate_tail,
)
from src.core.utils.graph_utils import (
    asummarize_oldest,
    get_prompts,
    get_vision_keywords,
    summarize_oldest,
)
from src.core.utils.text_utils import (
    FuzzyMatchResult,
    _extract_json_objects,
    _parse_llama_tool_calls,
    _sanitize_json_string,
    fuzzy_find_text,
    normalize_for_fuzzy_match,
    truncate_line,
)

__all__ = [
    "DEFAULT_MAX_BYTES",
    "DEFAULT_MAX_LINES",
    "GREP_MAX_LINE_LENGTH",
    "TruncationResult",
    "format_size",
    "truncate_head",
    "truncate_tail",
    "truncate_line",
    "resolve_to_cwd",
    "resolve_read_path",
    "detect_line_ending",
    "normalize_to_lf",
    "restore_line_endings",
    "strip_bom",
    "generate_diff_string",
    "FuzzyMatchResult",
    "normalize_for_fuzzy_match",
    "fuzzy_find_text",
    "_sanitize_json_string",
    "_extract_json_objects",
    "_parse_llama_tool_calls",
    "get_vision_keywords",
    "get_prompts",
    "summarize_oldest",
    "asummarize_oldest",
]
