"""P1 Cron suggestion engine — propose automations based on conversation patterns.

Ported from Hermes Agent's ``cron/suggestions.py`` (260 LOC) +
``cron/suggestion_catalog.py`` (154 LOC).

The suggestion engine observes what the user asks the agent to do
repeatedly and proposes cron jobs that would automate those tasks.
Suggestions are stored in a persistent JSON file
(``~/.nia/cron/suggestions.json``) with a lifecycle:

  - ``pending`` — proposed, waiting for the user to accept/dismiss.
  - ``accepted`` — user accepted; a cron job was created.
  - ``dismissed`` — user dismissed; won't be re-proposed (unless cleared).

Suggestions are generated by the background review loop (which runs
after each turn) and surfaced to the user via the ``/suggestions`` slash
command or the dashboard.

Usage::

    from niaharness.cron.suggestions import (
        add_suggestion, list_pending, accept_suggestion, dismiss_suggestion,
    )

    # After detecting a repeatable pattern:
    add_suggestion(
        ref="check-email-morning",
        title="Check email every morning",
        description="You ask about email every morning. Want me to automate this?",
        blueprint_key="important-mail",
        blueprint_values={"interval_min": "60", "deliver": "origin"},
    )

    # User accepts:
    spec = accept_suggestion("check-email-morning")
    if spec:
        upsert_cron_job(spec)
"""

from __future__ import annotations

import json
import logging
import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


def _get_nia_home() -> Path:
    """Return NIA_HOME (default ~/.nia)."""
    try:
        from niaharness.config.paths import get_nia_home
        return Path(get_nia_home())
    except Exception:
        return Path(os.environ.get("NIA_HOME", os.path.expanduser("~/.nia")))


def _ensure_dir() -> Path:
    """Ensure the cron suggestions directory exists."""
    cron_dir = _get_nia_home() / "cron"
    cron_dir.mkdir(parents=True, exist_ok=True)
    return cron_dir


def _suggestions_path() -> Path:
    """Return the path to the suggestions JSON file."""
    return _ensure_dir() / "suggestions.json"


def _secure_file(path: Path) -> None:
    """Set restrictive permissions on the suggestions file (0600)."""
    try:
        os.chmod(path, 0o600)
    except (OSError, NotImplementedError):
        pass  # Non-POSIX systems.


def _load_raw() -> Dict[str, Any]:
    """Load the raw suggestions data.

    Returns a dict with "suggestions" (list) + "version" (int).
    Returns an empty structure if the file doesn't exist or is corrupt.
    """
    path = _suggestions_path()
    try:
        raw = path.read_text(encoding="utf-8")
        data = json.loads(raw)
        if isinstance(data, dict) and isinstance(data.get("suggestions"), list):
            return data
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        pass
    return {"suggestions": [], "version": 1}


def _save_raw(data: Dict[str, Any]) -> None:
    """Save the raw suggestions data."""
    path = _suggestions_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        path.write_text(
            json.dumps(data, indent=2, default=str), encoding="utf-8"
        )
        _secure_file(path)
    except OSError as exc:
        logger.warning("Could not save cron suggestions: %s", exc)


def load_suggestions() -> List[Dict[str, Any]]:
    """Load all suggestions (all statuses)."""
    return _load_raw().get("suggestions", [])


def list_pending() -> List[Dict[str, Any]]:
    """List pending suggestions (not yet accepted or dismissed)."""
    return [s for s in load_suggestions() if s.get("status") == "pending"]


def list_accepted() -> List[Dict[str, Any]]:
    """List accepted suggestions."""
    return [s for s in load_suggestions() if s.get("status") == "accepted"]


def list_dismissed() -> List[Dict[str, Any]]:
    """List dismissed suggestions."""
    return [s for s in load_suggestions() if s.get("status") == "dismissed"]


def get_suggestion(ref: str) -> Optional[Dict[str, Any]]:
    """Get a suggestion by its ref (unique identifier)."""
    for s in load_suggestions():
        if s.get("ref") == ref:
            return s
    return None


def add_suggestion(
    ref: str,
    title: str,
    description: str,
    *,
    blueprint_key: Optional[str] = None,
    blueprint_values: Optional[Dict[str, Any]] = None,
    prompt: Optional[str] = None,
    schedule: Optional[str] = None,
    deliver: str = "origin",
    origin: Optional[Dict[str, Any]] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> bool:
    """Add a new suggestion. Returns True if added, False if ref already exists.

    Args:
        ref: Unique identifier (e.g. "check-email-morning").
        title: Short title.
        description: What the suggestion is about.
        blueprint_key: Optional blueprint key to fill when accepted.
        blueprint_values: Optional slot values for the blueprint.
        prompt: Optional direct prompt (if no blueprint).
        schedule: Optional cron expression (if no blueprint).
        deliver: Delivery target ("origin", "local", platform name).
        origin: Optional origin dict for deliver=origin.
        metadata: Optional extra metadata.
    """
    data = _load_raw()
    suggestions = data.get("suggestions", [])

    # Don't re-add if the ref already exists.
    for s in suggestions:
        if s.get("ref") == ref:
            # If it was dismissed, don't re-add (respect the user's choice).
            if s.get("status") == "dismissed":
                return False
            # If it's pending or accepted, update it.
            s.update({
                "title": title,
                "description": description,
                "blueprint_key": blueprint_key,
                "blueprint_values": blueprint_values,
                "prompt": prompt,
                "schedule": schedule,
                "deliver": deliver,
                "origin": origin,
                "metadata": metadata or {},
                "updated_at": time.time(),
            })
            _save_raw(data)
            return True

    suggestion: Dict[str, Any] = {
        "ref": ref,
        "title": title,
        "description": description,
        "blueprint_key": blueprint_key,
        "blueprint_values": blueprint_values,
        "prompt": prompt,
        "schedule": schedule,
        "deliver": deliver,
        "origin": origin,
        "metadata": metadata or {},
        "status": "pending",
        "created_at": time.time(),
        "updated_at": time.time(),
    }
    suggestions.append(suggestion)
    data["suggestions"] = suggestions
    _save_raw(data)
    return True


def _set_status(ref: str, status: str) -> bool:
    """Set the status of a suggestion. Returns True if found + updated."""
    data = _load_raw()
    suggestions = data.get("suggestions", [])
    for s in suggestions:
        if s.get("ref") == ref:
            s["status"] = status
            s["updated_at"] = time.time()
            _save_raw(data)
            return True
    return False


def dismiss_suggestion(ref: str) -> bool:
    """Dismiss a suggestion. Returns True if found + dismissed."""
    return _set_status(ref, "dismissed")


def accept_suggestion(
    ref: str,
    *,
    origin: Optional[Dict[str, Any]] = None,
) -> Optional[Dict[str, Any]]:
    """Accept a suggestion. Returns the cron job spec, or None if not found.

    The spec can be passed directly to ``upsert_cron_job``. If the
    suggestion has a ``blueprint_key``, the blueprint is filled with
    ``blueprint_values``. Otherwise, the direct ``prompt`` + ``schedule``
    are used.
    """
    suggestion = get_suggestion(ref)
    if suggestion is None:
        return None

    # Mark as accepted.
    _set_status(ref, "accepted")

    # Build the cron job spec.
    spec: Dict[str, Any] = {
        "name": suggestion.get("title", ref),
        "deliver": suggestion.get("deliver", "origin"),
    }

    # Use the provided origin, or fall back to the suggestion's origin.
    effective_origin = origin or suggestion.get("origin")
    if effective_origin:
        spec["origin"] = effective_origin

    blueprint_key = suggestion.get("blueprint_key")
    if blueprint_key:
        from niaharness.cron.blueprint_catalog import fill_blueprint, get_blueprint
        bp = get_blueprint(blueprint_key)
        if bp is None:
            logger.warning("Suggestion %r: blueprint %r not found", ref, blueprint_key)
            return None
        values = suggestion.get("blueprint_values") or {}
        try:
            filled = fill_blueprint(bp, values, origin=effective_origin)
            spec.update(filled)
        except Exception as exc:
            logger.error("Suggestion %r: blueprint fill failed: %s", ref, exc)
            return None
    else:
        # Direct prompt + schedule.
        spec["prompt"] = suggestion.get("prompt", "")
        spec["schedule"] = suggestion.get("schedule", "* * * * *")
        if not spec["prompt"]:
            logger.warning("Suggestion %r: no prompt and no blueprint", ref)
            return None

    return spec


def clear_resolved() -> int:
    """Remove all accepted + dismissed suggestions. Returns count removed."""
    data = _load_raw()
    suggestions = data.get("suggestions", [])
    before = len(suggestions)
    data["suggestions"] = [
        s for s in suggestions if s.get("status") == "pending"
    ]
    removed = before - len(data["suggestions"])
    if removed > 0:
        _save_raw(data)
    return removed


def clear_all() -> int:
    """Remove ALL suggestions (including pending). Returns count removed."""
    data = _load_raw()
    count = len(data.get("suggestions", []))
    data["suggestions"] = []
    _save_raw(data)
    return count


__all__ = [
    "accept_suggestion",
    "add_suggestion",
    "clear_all",
    "clear_resolved",
    "dismiss_suggestion",
    "get_suggestion",
    "list_accepted",
    "list_dismissed",
    "list_pending",
    "load_suggestions",
]
